### ISSUE TITLE
this.handlerFn is not a function

### ISSUE THREAD

**Issue by Caoimhin89** [nikolaymatrosov/yc-apollo-function#1]
Getting the following error when opening the Endpoint link on my yandex cloud function.

`{"errorMessage":"this.handlerFn is not a function","errorType":"TypeError","stackTrace":[{"function":"vp.<anonymous>","file":"/function/runtime/bootstrap","line":262,"column":116},{"function":"Generator.throw","file":null,"line":null,"column":null},{"function":"t","file":"/function/runtime/bootstrap","line":229,"column":184}]}`

Here are the contents of my package.json file:

```
{
    "name": "serverless-yandex-graphql",
    "version": "1.0.0",
    "dependencies": {
        "apollo-server-core": "^2.18.2",
        "graphql": "^15.3.0",
        "ydb-sdk": "^1.4.3"
    },
    "devDependencies": {
        "@types/fs-capacitor": "^2.0.0",
        "@types/node": "^17.0.35",
        "@types/pino": "latest",
        "serverless": "^2.8.0",
        "serverless-yandex-cloud": "latest",
        "typescript": "^4.6.4"
    }
}
```

**Comment by nikolaymatrosov** [comment]
There is no `handlerFn` in the code in this repo. So I guess it is somewhere in the code you wrote in your project.
Another guess is that you might pass the wrong value to the `handler` property in the serverless.yml. So the Yandex Cloud serverless runtime fails to find the specified handlerFn. Or maybe it is not a function, as it is said in the error message.
Unfortunately, I can not say more without seeing the code.

You might try to open an issue in [the cloud support](https://console.cloud.yandex.ru/support?section=contact). They probably could help more.

Please be advised that this repo was written as a one-time example two years ago, and I have not been maintaining it since then.
